name: Go

on: [push, pull_request]

jobs:

    gobuild:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Go
                uses: actions/setup-go@v2
                with:
                    go-version: 1.17

            -   name: go build
                run: go build -v ./...

    govet:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Go
                uses: actions/setup-go@v2
                with:
                    go-version: 1.17

            -   name: go vet
                run: go vet -v ./...

    gotest:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Go
                uses: actions/setup-go@v2
                with:
                    go-version: 1.17

            -   name: go test
                env:
                    token: ${{ secrets.TOKEN }}
                run: go test -v ./...

    golint:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Go
                uses: actions/setup-go@v2
                with:
                    go-version: 1.17

            -   name: golint
                uses: Jerome1337/golint-action@v1.0.2
                with:
                    golint-path: './...'
